
SELECT GETDATE()

--DATEPART
SELECT DATEPART(YYYY,GETDATE())
SELECT DATEPART(MM,GETDATE())
SELECT DATEPART(DD,GETDATE())

--DATEADD
SELECT DATEADD(d,4,GETDATE())
SELECT DATEADD(DAY,4,'12/04/1999')
SELECT DATEADD(MONTH,4,GETDATE())
SELECT DATEADD(YEAR,4,GETDATE())

SELECT * FROM [Production].[WorkOrder]

SELECT WORKORDERID,PRODUCTID,STARTDATE,ENDDATE ,DATEDIFF(DAY,STARTDATE,ENDDATE) AS DUEDATE FROM [Production].[WorkOrder]


SELECT DATEADD(DAY,-(DATEPART(DAY,GETDATE())-1),GETDATE())
