USE DEMO
CREATE TABLE EMP_1(EMPID INT , FIRSTNAME TEXT , LASTNAME TEXT)
INSERT INTO EMP_1 VALUES(1,'RAJU','YADAV')
INSERT INTO EMP_1 VALUES(2,'AVNISH','CHOWDARY')
INSERT INTO EMP_1 VALUES(3,'KARTIK','ARYAN')

CREATE TABLE EMPSAL(EMPID INT , SALARY FLOAT)
INSERT INTO EMPSAL VALUES(1,25000)
INSERT INTO EMPSAL VALUES(2,30000)
INSERT INTO EMPSAL VALUES(3,34000)

SELECT * FROM EMP_1
SELECT * FROM EMPSAL

--INNER JOIN
SELECT T1.FIRSTNAME,T1.LASTNAME,T2.SALARY FROM EMP_1 T1 INNER JOIN EMPSAL T2 ON T1.EMPID=T2.EMPID 


--LEFT JOIN
CREATE TABLE MYPHONE(EMPID INT , PHONE INT)
INSERT INTO MYPHONE VALUES(1,924887)
INSERT INTO MYPHONE VALUES(2,929075)

SELECT * FROM EMP_1
SELECT * FROM MYPHONE


SELECT T1.FIRSTNAME,T1.LASTNAME ,T2.PHONE FROM EMP_1 T1 LEFT JOIN MYPHONE T2 ON T1.EMPID=T2.EMPID

--RIGHT JOIN
CREATE TABLE MY_PARKING(EMPID INT , PARKING VARCHAR(20))
INSERT INTO MY_PARKING VALUES(1,'A1')
INSERT INTO MY_PARKING VALUES(2,'A2')

SELECT * FROM EMP_1
SELECT * FROM MY_PARKING


SELECT T1.PARKING,T2.FIRSTNAME,T2.LASTNAME FROM MY_PARKING T1 RIGHT JOIN EMP_1 T2 ON T1.EMPID=T2.EMPID

--FULL JOIN
CREATE TABLE MYCUSTOMER(CUST_ID INT, CUSTNAME VARCHAR(20))
INSERT INTO MYCUSTOMER VALUES(1,'VAISHNAV')
INSERT INTO MYCUSTOMER VALUES(3,'AVNISH')

CREATE TABLE MYORDER(ORDERID INT , ORDERNAME VARCHAR(20),CUST_ID INT)
INSERT INTO MYORDER VALUES(1234,'BURGER',1)
INSERT INTO MYORDER VALUES(1245,'SANDWICH',2)
INSERT INTO MYORDER VALUES(1366,'ICE-CREAM',7)
INSERT INTO MYORDER VALUES(1423,'PIZZA',8)

SELECT * FROM MYCUSTOMER
SELECT * FROM MYORDER

SELECT T1.CUSTNAME,T2.ORDERID,T2.ORDERNAME FROM MYCUSTOMER T1 FULL JOIN MYORDER T2 ON T1.CUST_ID=T2.CUST_ID


--CROSS JOIN
SELECT * FROM MYCUSTOMER
SELECT * FROM MYORDER
SELECT * FROM MYCUSTOMER CROSS JOIN MYORDER
--OR YOU CAN ALSO WRITE AS
SELECT * FROM MYCUSTOMER,MYORDER




