--STORED PROCEDURES
CREATE PROCEDURE DEMO
AS 
SET NOCOUNT ON
SELECT * FROM [HumanResources].[Shift]

EXECUTE DEMO


CREATE PROCEDURE DEMO1
AS 
SET NOCOUNT OFF --gives the message regarding no.of rows effected
SELECT * FROM [HumanResources].[Shift]

EXECUTE DEMO1
--OR
EXEC DEMO1

--DELETE PROCEDURE
DROP PROC DEMO1


--PARAMETERIZED PROCEDURE
CREATE PROCEDURE DEMO2
@PARAMETERNAME VARCHAR(20)
AS
SET NOCOUNT ON
SELECT * FROM [HumanResources].[Shift]
WHERE NAME=@PARAMETERNAME

EXEC DEMO2 @PARAMETERNAME="DAY"
--OR
EXEC DEMO2 "DAY" 
--VALUES SHOULD BE PASSED IN THE ORDER OF CREATION


CREATE PROCEDURE DEMO3
@PARAMETERNAME VARCHAR(20)="EVENING" --SETTING PARAMETER TO DEFAULT SO IN CASE WHILE USING THIS PROCEDURE IF PARAMETER IS NOT PASSED IT TAKES THE DEFAULT VALUE
AS
SET NOCOUNT ON
SELECT * FROM [HumanResources].[Shift]
WHERE NAME=@PARAMETERNAME

EXEC DEMO3 --NO PARAMETERS PASSED BUT GAVE RESULT WHICH HAS EVENING IN IT AS DEFAULT
EXEC DEMO3 @PARAMETERNAME ="DAY"
EXEC DEMO3 "DAY"

--OUTPUT PARAMETERS
CREATE PROC DEMO4
@TopShift varchar(20) OUTPUT
AS
SET @TopShift =(SELECT TOP(1) ShiftID FROM [HumanResources].[Shift])

DECLARE @outputresult varchar(20)
EXEC DEMO4 @outputresult OUTPUT
SELECT @outputresult

--RETURNING VALUES FROM PROCEDURES
CREATE PROC DEMO5
AS
RETURN 12

DECLARE @STORERESULT INT
EXEC @STORERESULT=DEMO5
SELECT @STORERESULT