CREATE TABLE EMP(NAME VARCHAR(20),DEPT VARCHAR(20),AGE INT,SALARY INT)
INSERT INTO EMP VALUES('ARJUN','FINANCE',23,45000)
INSERT INTO EMP VALUES('KARAN','FINANCE',34,55000)
INSERT INTO EMP VALUES('SALMAN','FINANCE',30,37000)
INSERT INTO EMP VALUES('AMIR','SALES',33,38000)
INSERT INTO EMP VALUES('KARTIK','SALES',38,45000)
INSERT INTO EMP VALUES('DHRUV','FINANCE',36,55000)


SELECT * FROM EMP

SELECT *,AVG(SALARY) OVER(PARTITION BY DEPT ORDER BY AGE) AS AVGSAL FROM EMP

SELECT ROW_NUMBER() OVER(PARTITION BY DEPT ORDER BY SALARY DESC) AS EMPROWNO,NAME,DEPT ,SALARY ,RANK() OVER(PARTITION BY DEPT ORDER BY SALARY DESC) AS RANK ,DENSE_RANK() OVER(PARTITION BY DEPT ORDER BY SALARY DESC) AS DENSE_RANK FROM EMP

SELECT ROW_NUMBER() OVER(PARTITION BY DEPT ORDER BY SALARY ) AS EMPROWNO,NAME,DEPT ,SALARY ,RANK() OVER(PARTITION BY DEPT ORDER BY SALARY ) AS RANK ,DENSE_RANK() OVER(PARTITION BY DEPT ORDER BY SALARY ) AS DENSE_RANK FROM EMP


SELECT * FROM [Person].[Address]

SELECT ROW_NUMBER() OVER(ORDER BY PostalCode)AS 'ROW',
	PostalCode,RANK() OVER(ORDER BY PostalCode) AS 'RANK',
	DENSE_RANK() OVER(ORDER BY PostalCode) AS 'DENSE_RANK',
	NTILE(10) OVER(ORDER BY PostalCode) AS 'NTILE' FROM [Person].[Address] 
	WHERE PostalCode IN ('98052','98027','98055','97205')